# Generated by Django 3.0.1 on 2019-12-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='excluido',
            field=models.BooleanField(default=0),
        ),
    ]
