# Generated by Django 3.0.1 on 2019-12-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_excluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
