# Generated by Django 3.0.1 on 2019-12-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_produto_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='file',
            field=models.FileField(default='media/sem_image.png', null=True, upload_to=''),
        ),
    ]
