# Generated by Django 3.0.1 on 2019-12-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20191231_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='file',
            field=models.FileField(default='sem_image.png', null=True, upload_to=''),
        ),
    ]
