# Generated by Django 3.0.1 on 2020-01-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
    ]
