# Generated by Django 3.0.1 on 2019-12-31 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_auto_20191227_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='funcionario',
        ),
    ]
